/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import jaco.mp3.player.MP3Player;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.*;
import java.awt.print.*;
import java.io.File;
import javax.swing.JTable;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author USER
 */
public class Pengunjung extends javax.swing.JFrame {

    
    JasperDesign jd;
    //.Map param = new HashMap(;
    private void kosong_form(){
        MP3Player clearMusic = new MP3Player(new File("src/sound/clear.mp3"));
        clearMusic.play();
        NIK.setEditable(true);
        NIK.setText(null);
        NAMA.setText(null);
        STATUS.setSelectedItem(this);
        ALAMAT.setText(null);
        EMAIL.setText(null);
        NO_TELP.setText(null);
    }
    
        private void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NIK");
        model.addColumn("Nama Pengunjung");
        model.addColumn("Status");
        model.addColumn("Alamat");
        model.addColumn("Email");
        model.addColumn("No HP");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pengunjung";
            java.sql.Connection conn = (Connection)KonfigDB.configDBConnection();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5), res.getString(6)}); 
            }
            
            TabelPengunjung.setModel(model);
            
        }catch(SQLException e){
            System.out.println("ERROR : " + e.getMessage());
        }
        
    }
        
    /**
     * Creates new form Pengunjung
     */
    public Pengunjung() {
        initComponents();
        tampil_data();
        kosong_form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cetakDialog = new javax.swing.JDialog();
        comboCat = new javax.swing.JComboBox<>();
        buttonCetakCat = new javax.swing.JButton();
        BackGround = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPengunjung = new javax.swing.JTable();
        TambahData = new javax.swing.JButton();
        SimpanData = new javax.swing.JButton();
        EditData = new javax.swing.JButton();
        HapusData = new javax.swing.JButton();
        BatalData = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        NO_TELP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        STATUS = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NIK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Cetak = new javax.swing.JButton();

        cetakDialog.setBackground(new java.awt.Color(122, 72, 211));
        cetakDialog.setMinimumSize(new java.awt.Dimension(200, 80));
        cetakDialog.setResizable(false);
        cetakDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Umum", "Siswa", "Mahasiswa", "Turis", "VIP" }));
        comboCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCatActionPerformed(evt);
            }
        });
        cetakDialog.getContentPane().add(comboCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonCetakCat.setText("CETAK");
        buttonCetakCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCetakCatActionPerformed(evt);
            }
        });
        cetakDialog.getContentPane().add(buttonCetakCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar Pengunjung Museum Negeri NTB");
        setMinimumSize(new java.awt.Dimension(735, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGround.setBackground(new java.awt.Color(54, 33, 89));
        BackGround.setForeground(new java.awt.Color(54, 33, 89));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DAFTAR PENGUNJUNG ");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MUSEUM NEGERI NUSA TENGGARA BARAT");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo ntb.png"))); // NOI18N

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel8))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(26, 26, 26))
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 100));

        jPanel1.setBackground(new java.awt.Color(122, 72, 211));

        TabelPengunjung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPengunjung.setGridColor(new java.awt.Color(255, 255, 255));
        TabelPengunjung.setSelectionBackground(new java.awt.Color(51, 0, 153));
        TabelPengunjung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPengunjungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPengunjung);

        TambahData.setBackground(new java.awt.Color(51, 0, 102));
        TambahData.setForeground(new java.awt.Color(255, 255, 255));
        TambahData.setText("Tambah");
        TambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahDataActionPerformed(evt);
            }
        });

        SimpanData.setBackground(new java.awt.Color(51, 0, 102));
        SimpanData.setForeground(new java.awt.Color(255, 255, 255));
        SimpanData.setText("Simpan");
        SimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanDataActionPerformed(evt);
            }
        });

        EditData.setBackground(new java.awt.Color(51, 0, 102));
        EditData.setForeground(new java.awt.Color(255, 255, 255));
        EditData.setText("Edit");
        EditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDataActionPerformed(evt);
            }
        });

        HapusData.setBackground(new java.awt.Color(51, 0, 102));
        HapusData.setForeground(new java.awt.Color(255, 255, 255));
        HapusData.setText("Hapus");
        HapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDataActionPerformed(evt);
            }
        });

        BatalData.setBackground(new java.awt.Color(51, 0, 102));
        BatalData.setForeground(new java.awt.Color(255, 255, 255));
        BatalData.setText("Batal");
        BatalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalDataActionPerformed(evt);
            }
        });

        Keluar.setBackground(new java.awt.Color(51, 0, 102));
        Keluar.setForeground(new java.awt.Color(255, 255, 255));
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Telepon");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        ALAMAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALAMATActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");

        STATUS.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Siswa", "Mahasiswa", "Turis", "VIP" }));
        STATUS.setBorder(null);
        STATUS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        STATUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STATUSActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIK");

        Cetak.setBackground(new java.awt.Color(51, 0, 102));
        Cetak.setForeground(new java.awt.Color(255, 255, 255));
        Cetak.setText("Cetak");
        Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(TambahData)
                        .addGap(18, 18, 18)
                        .addComponent(SimpanData)
                        .addGap(18, 18, 18)
                        .addComponent(EditData)
                        .addGap(18, 18, 18)
                        .addComponent(HapusData)
                        .addGap(18, 18, 18)
                        .addComponent(BatalData)
                        .addGap(18, 18, 18)
                        .addComponent(Keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cetak))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(NO_TELP, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NO_TELP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahData)
                    .addComponent(SimpanData)
                    .addComponent(EditData)
                    .addComponent(HapusData)
                    .addComponent(BatalData)
                    .addComponent(Keluar)
                    .addComponent(Cetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 720, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public boolean cekKosong(){
        if (NIK.getText().isBlank() || NAMA.getText().isBlank() || ALAMAT.getText().isBlank() || EMAIL.getText().isBlank() || NO_TELP.getText().isBlank()){
            return false;
        }
        else{
            return true;
        }
    }
    
    private void TambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahDataActionPerformed
        // TODO add your handling code here:
        kosong_form();
    }//GEN-LAST:event_TambahDataActionPerformed

    private void SimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanDataActionPerformed
        // TODO add your handling code here:
        try{
            if (cekKosong()) {
                String sql = "INSERT INTO pengunjung VALUES ('"+NIK.getText()+"','"+NAMA.getText()+"','"+STATUS.getSelectedItem()+"','"+ALAMAT.getText()+"','"+EMAIL.getText()+"','"+NO_TELP.getText()+"')";
                java.sql.Connection conn = (Connection)KonfigDB.configDBConnection();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                MP3Player sucMusic = new MP3Player(new File("src/sound/"));
                MP3Player music = new MP3Player(new File("src/sound/cetak.mp3"));
                music.play();
                JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil!");
                music.stop();
                tampil_data();
                kosong_form();
            }
            else{
                MP3Player invalidMusic = new MP3Player(new File("src/sound/invalid.mp3"));
                invalidMusic.play();
                JOptionPane.showMessageDialog(null, "Isi field yang kosong!");
                invalidMusic.stop();
            }
        }catch(HeadlessException | SQLException e ){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_SimpanDataActionPerformed

    private void EditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDataActionPerformed
        // TODO add your handling code here:
           try{
                if (cekKosong()) {
                     String sql = "UPDATE pengunjung SET nik='"+NIK.getText()+"', nama='"+NAMA.getText()+"', status='"+STATUS.getSelectedItem()+"', alamat='"+ALAMAT.getText()+"', email='"+EMAIL.getText()+"', no_telp='"+NO_TELP.getText()+"' WHERE nik='"+NIK.getText()+"'"; 
                     java.sql.Connection conn = (Connection)KonfigDB.configDBConnection();
                     java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                     pstm.execute();
                     MP3Player music = new MP3Player(new File("src/sound/cetak.mp3"));
                     music.play();
                     JOptionPane.showMessageDialog(null, "Edit Data Berhasil!");
                     music.stop();
                 }
                 else{
                     MP3Player invalidMusic = new MP3Player(new File("src/sound/invalid.mp3"));
                    invalidMusic.play();
                    JOptionPane.showMessageDialog(null, "Isi field yang kosong!");
                    invalidMusic.stop();
                 }
        }catch(HeadlessException | SQLException e ){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_form();
    }//GEN-LAST:event_EditDataActionPerformed

    private void HapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDataActionPerformed
        // TODO add your handling code here:
        try{
           String sql = "DELETE FROM pengunjung WHERE nik='"+NIK.getText()+"'";
           java.sql.Connection conn = (Connection)KonfigDB.configDBConnection();
           java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
           pstm.execute();
           MP3Player music = new MP3Player(new File("src/sound/delete.mp3"));
           music.play();
           JOptionPane.showMessageDialog(null, "Hapus Data Berhasil!");
           music.stop();
        }catch(HeadlessException | SQLException e ){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_form();
    }//GEN-LAST:event_HapusDataActionPerformed

    private void BatalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalDataActionPerformed
        // TODO add your handling code here:
        kosong_form();
    }//GEN-LAST:event_BatalDataActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        MP3Player music = new MP3Player(new File("src/sound/exit.mp3"));
        music.play();
        JOptionPane.showMessageDialog(null, "Sampai jumpa kembali!");
        music.stop();
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void TabelPengunjungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPengunjungMouseClicked
        // TODO add your handling code here:
        int baris = TabelPengunjung.rowAtPoint(evt.getPoint());
        String nik = TabelPengunjung.getValueAt(baris, 1).toString();
        NIK.setText(nik);
        
        String nama = TabelPengunjung.getValueAt(baris, 2).toString();
        NAMA.setText(nama);
        
        String status = TabelPengunjung.getValueAt(baris, 3).toString();
        STATUS.setSelectedItem(status);
        
        String  alamat = TabelPengunjung.getValueAt(baris, 4).toString();
        ALAMAT.setText(alamat);
        
        String email = TabelPengunjung.getValueAt(baris, 5).toString();
        EMAIL.setText(email);
        
        String no_telp = TabelPengunjung.getValueAt(baris, 6).toString();
        NO_TELP.setText(no_telp);
    }//GEN-LAST:event_TabelPengunjungMouseClicked

    private void ALAMATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALAMATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALAMATActionPerformed

    private void CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakActionPerformed
        MP3Player music = new MP3Player(new File("src/sound/cetak.mp3"));
        music.play();
        cetakDialog.setVisible(true);
        cetakDialog.setLocationRelativeTo(null);
        music.stop();
       
    }//GEN-LAST:event_CetakActionPerformed

    private void STATUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STATUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STATUSActionPerformed

    private void buttonCetakCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCetakCatActionPerformed
        String cat = comboCat.getSelectedItem().toString();
        String sql;
        if (cat.equals("Semua")){
            sql = "SELECT * FROM pengunjung";
        }
        else{
            sql = "SELECT * FROM pengunjung where status ='"+cat+"'";
        }
        String path = "C:\\Users\\voXlan\\Documents\\NetBeansProjects\\Daftar Pengunjung Museum\\src\\museumReport.jrxml";
        try {
            Connection conn = KonfigDB.configDBConnection();
            MP3Player music = new MP3Player(new File("src/sound/cetak.mp3"));
            music.play();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
            JasperPrint jp;
            JRResultSetDataSource jrd = new JRResultSetDataSource(rs);
            JasperReport jr = JasperCompileManager.compileReport(path);
            jp = JasperFillManager.fillReport(jr, null, jrd);
            JasperViewer.viewReport(jp, false);
            
        } catch (SQLException | JRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonCetakCatActionPerformed

    private void comboCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALAMAT;
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton BatalData;
    private javax.swing.JButton Cetak;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JButton EditData;
    private javax.swing.JButton HapusData;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField NO_TELP;
    private javax.swing.JComboBox<String> STATUS;
    private javax.swing.JButton SimpanData;
    private javax.swing.JTable TabelPengunjung;
    private javax.swing.JButton TambahData;
    private javax.swing.JButton buttonCetakCat;
    private javax.swing.JDialog cetakDialog;
    private javax.swing.JComboBox<String> comboCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
